#ifndef ELMYRAGLOBALDEFINES_HPP
#define ELMYRAGLOBALDEFINES_HPP

#define SERIAL_DEBUG
//#define SERIAL_DEBUG_TOUCH 

#define BIAS 512
#define AMP_MAX 511
#define POT_MAX 4095
#define LED_PIN_MAX 254
#define SMOOTHING_FACTOR_TUNE 60
#define SMOOTHING_FACTOR_NORMAL 5
#define SMOOTHING_FACTOR_TOUCH 5
#define POT_DEAD_ZONE_TUNE 1
#define POT_DEAD_ZONE_NORMAL 30
#define POT_TUNE_BASE 20000
#define POT_TUNE_SCALE 100
#define ENV_MAX 200
#define ENV_MIN 50
#define ENV_ATTACK 1
#define ENV_RELEASE 1
#define ENV_SPEED_FACTOR 128
#define ENV_BYPASS_ENABLE_TIME 1
#define AUDIO_BUF_SIZE 1000
#define AUDIO_BUF_PREFILL 100
#define DELAY_BUF_SIZE 12000
#define DELAY_POT_SCALE_MIX 4095
#define DELAY_POT_SCALE_TIME 500
#define DELAY_POT_SCALE_FEEDBACK 1023
#define DELAY_TIME_SLEW 500
#define DELAY_TIME_FINETUNE_POINT 1000
#define DELAY_TIME_FINETUNE_FACTOR 2
#define OSC_WAVE_SLEW_LOW 1
#define OSC_WAVE_SLEW_HIGH 5
#define OSC_SLEW_SCALE 4
#define OSC_MOD_AMOUNT_MAX 24
#define CLOCK_RATE 48000000
#define SAMPLE_RATE 24000
#define RELAX_TIME 5
#define IO_UPDATE_FREQ 25
#define CHAOS_LFO_PERIOD_MAX 4000
#define CHAOS_LFO_PERIOD_MIN 500
#define NUM_VOICES 3

#define PIN_IN_GSR_1 A3
#define PIN_IN_GSR_2 A2
#define PIN_IN_GSR_3 A1
#define PIN_IN_TUNE_1 A5
#define PIN_IN_TUNE_2 20
#define PIN_IN_TUNE_3 21
#define PIN_IN_MOD A4
#define PIN_IN_DELAY_FEEDBACK 22
#define PIN_IN_DELAY_TIME 23
#define PIN_IN_DELAY_MIX 25
#define PIN_IN_WAVE_1 7
#define PIN_IN_WAVE_2 12
#define PIN_IN_WAVE_3 2
#define PIN_IN_ENV_1 SCK
#define PIN_IN_ENV_2 MOSI
#define PIN_IN_ENV_3 MISO
#define PIN_OUT_AUDIO A0
#define PIN_OUT_ENV_1 13
#define PIN_OUT_ENV_2 11
#define PIN_OUT_ENV_3 10

#endif
